on: [push]
name: check
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup HLint'
        uses: haskell/actions/hlint-setup@v2

      - name: 'Run HLint'
        uses: haskell/actions/hlint-run@v2
        with:
          path: src/
          fail-on: warning

  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup GHC with Stack'
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
          # TODO /home/runner/.stack/programs/x86_64-linux/ghc-tinfo6-9.4.1/lib/ghc-9.4.1/bin/ghc-pkg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/.stack/programs/x86_64-linux/ghc-tinfo6-9.4.1/lib/ghc-9.4.1/bin/../lib/x86_64-linux-ghc-9.4.1/libHSrts-1.0.2-ghc9.4.1.so)
          # stack-no-global: true
          # stack-setup-ghc: false

      - name: 'Build all'
        run: stack build

      - name: 'Run task1 test'
        if: ${{ always() }}
        run: N=1; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task2 test'
        if: ${{ always() }}
        run: N=2; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task3 test'
        if: ${{ always() }}
        run: N=3; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task4 test'
        if: ${{ always() }}
        run: N=4; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task5 test'
        if: ${{ always() }}
        run: N=5; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task6 test'
        if: ${{ always() }}
        run: N=6; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task7 test'
        if: ${{ always() }}
        run: N=7; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task8 test'
        if: ${{ always() }}
        run: N=8; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task9 test'
        if: ${{ always() }}
        run: N=9; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task10 test'
        if: ${{ always() }}
        run: N=10; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'

      - name: 'Run task11 test'
        if: ${{ always() }}
        run: N=11; stack test --ta "task$N" &> tmp$N.txt; cat tmp$N.txt | grep -E '### Error in:|### Failure in:' | wc -l | grep '0'
